### ISSUE TITLE
Unable to run app on M+ Devices

### ISSUE THREAD

**Issue by merlinJeyakumar** [AminRahkan/SipApp#3]
Getting below error while trying to run 

java.lang.RuntimeException: Unable to start service org.abtollc.service.ABTOSipService@2c72606 with Intent { act=org.abtollc.service.ABTOSipService cmp=aminrahkan7.sipapp/org.abtollc.service.ABTOSipService (has extras) }: java.lang.SecurityException: Failed to find provider org.abtollc.db for user 0; expected to find a valid ContentProvider for this authority
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3724)
        at android.app.ActivityThread.access$1600(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.SecurityException: Failed to find provider org.abtollc.db for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:779)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1972)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1961)
        at org.abtollc.service.ABTOSipService.registerBroadcasts(ABTOSipService.java:1823)
        at org.abtollc.service.ABTOSipService.loadStack(ABTOSipService.java:2027)
        at org.abtollc.service.ABTOSipService.onStartCommand(ABTOSipService.java:1886)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
        at android.app.ActivityThread.access$1600(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.content.ContentService.registerContentObserver(ContentService.java:340)
        at android.content.IContentService$Stub.onTransact(IContentService.java:76)
        at com.android.server.content.ContentService.onTransact(ContentService.java:262)
        at android.os.Binder.execTransact(Binder.java:731)

**Comment by karabimaity17** [comment]
I am also getting this error
